modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="little_critters"
version="${file.jarVersion}"
displayName="Little Critters Mod"
logoFile="little_critters.png"
authors="grillo78"
description='''
Little critters is a mod that intends to add realistic small critters with realistic behavior to the game like ants, flies and much more!
'''

[[dependencies.little_critters]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.little_critters]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
